name: Staging CD

on:
  push:
    tags:
      - v[12].[0-9]+.[0-9]+-stg

jobs:
  build-ci-cd-office-desk-stage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry for stage
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies for stage
        run: |
          make install
