name: Staging CD

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-stg

jobs:
  build-ci-cd-office-desk-stage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry for stage
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies for stage
        run: |
          make install

      - name: Get OLD VERSION
        run: |
          echo "${{ env.OLD_VERSION }}"

      - name: Get new version
        run: |
          python get_version.py

      - name: Generate production message from 1
        run: |
          source .venv/bin/activate && ENVIRONMENT='production' VERSION=$GITHUB_REF_NAME python generate_release_msg.py

      - name: Generate production message from 2
        run: |
          source .venv/bin/activate && ENVIRONMENT='production' VERSION=${{  github.ref_name }} python generate_release_msg.py
