name: General CI/CD

on:
  push:
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+-stg
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
      - release_version_tools/setup.py
  pull_request:
    branches:
      - main

jobs:
  build-ci-cd-office-desk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          make install

      - name: Create (and push) an empty commit if there is just one commit on the current branch
        if: github.event_name == 'pull_request'
        run: |
          CURRENT_BRANCH_NUM_COMMITS=`git log --oneline origin/main..HEAD | wc -l`
          if [ "$CURRENT_BRANCH_NUM_COMMITS" -le "2" ] ; then
            git switch ${{ github.head_ref }}
            git config user.email "no-reply+github-actions@ioet.com"
            git config user.name "ioet ops"
            git commit --allow-empty -m 'fix: Autogenerated commit to ensure that there are at least two commits on all branches/PRs [skip ci]'
            git push
          else
            echo "We already have multiple commits on the current branch"
          fi

      - name: Python Semantic Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          pip install python-semantic-release
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          DEBUG='semantic_release.*' semantic-release publish -D commit_author="github-actions <action@github.com>"
        env:
          github_token: ${{secrets.GH_TOKEN}}

