name: General CI/CD

on:
  push:
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+-stg
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md
      - setup.py
  pull_request:
    branches:
      - main

jobs:
  build-ci-cd-office-desk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          make install

      - name: Generate production message
        run: |
          source .venv/bin/activate && ENVIRONMENT='production' VERSION='0.19.0' python generate_release_msg.py

      - name: Generate stage message
        run: |
          source .venv/bin/activate && python generate_release_msg.py

      - name: Get version
        run: |
          echo 'OLD_VERSION<<EOF' >> $GITHUB_ENV
          python get_version.py >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      
      - name: Use version
        run: |
          echo "${{ env.OLD_VERSION }}" 

      - name: Python Semantic Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          pip install python-semantic-release
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          DEBUG='semantic_release.*' semantic-release publish -D commit_author="github-actions <action@github.com>"
        env:
          github_token: ${{secrets.GH_TOKEN}}

